add shfmt

diff --git a/bin/apply b/bin/apply
--- a/bin/apply
+++ b/bin/apply
@@ -3,13 +3,13 @@
 # Exit immediately if a command exits with a non-zero status
 set -e
 
-HOST_CLOUD=$(grep -w "provider" terraform.tfvars | \
-             cut -d "=" -f 2- | \
-             awk -F\" '{print $(NF-1)}')
+HOST_CLOUD=$(grep -w "provider" terraform.tfvars |
+  cut -d "=" -f 2- |
+  awk -F\" '{print $(NF-1)}')
 
 # Check for recognized cloud provider
-if ! grep -qw "$HOST_CLOUD" <<< "openstack gce azure aws"; then
-  >&2 echo "Error: unrecognized host cloud '$HOST_CLOUD' in config file terraform.tfvars"
+if ! grep -qw "$HOST_CLOUD" <<<"openstack gce azure aws"; then
+  echo >&2 "Error: unrecognized host cloud '$HOST_CLOUD' in config file terraform.tfvars"
   exit 1
 fi
 
