fixed wrong echo - exit

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -27,7 +27,7 @@ fi
 for group_id in $LOCAL_GROUP_IDS; do
 
   # create group with $group_id if it doesnt exist
-  if ! getent group "$group_id"; then
+  if ! getent group "$group_id" > /dev/null 2>&1; then
     addgroup --quiet --gid "$group_id" "group$group_id"
   fi
 
@@ -56,7 +56,7 @@ for arg in "$@"; do
 done
 
 # enter KubeNow user config path
-cd "/KubeNow_config" || echo "Error: could not change dir to /KuneNow_config, exiting."  && exit 1
+cd "/KubeNow_config" || ( echo "Error: could not change dir to /KuneNow_config, exiting."; exit 1 )
 
 # run command as above created user via ssh-wrapper script that adds the
 # ssh-agent to this execution environment
