more styling

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -11,7 +11,7 @@ set -e
 
 # Add and run as local user if LOCAL_USER_ID is passed in at runtime
 if [ -z "$LOCAL_USER_ID" ]; then
-  echo "LOCAL_USER_ID must be set in the environment when running this container, exiting."
+  echo "LOCAL_USER_ID must be set in the environment when running this container, exiting." >&2
   exit 1
 fi
 
@@ -29,22 +29,22 @@ username=$(getent passwd "$LOCAL_USER_ID" | cut -d: -f1)
 # create groups with $LOCAL_GROUP_IDS and add them to user
 for group_id in $LOCAL_GROUP_IDS; do
 
-  # create group with $group_id if it doesnt exist
+  # create group with $group_id if it doesn't exist
   if ! getent group "$group_id" >/dev/null 2>&1; then
     addgroup --quiet --gid "$group_id" "group$group_id"
   fi
 
   # get groupname with $group_id
-  GROUPNAME=$(getent group "$group_id" | cut -d: -f1)
+  groupname=$(getent group "$group_id" | cut -d: -f1)
 
   # add group to user
-  adduser --quiet "$username" "$GROUPNAME" >/dev/null 2>&1
+  adduser --quiet "$username" "$groupname" >/dev/null 2>&1
 
 done
 
 # add KubeNow bin path (works with gosu - environment variables are kept
-# when swiching user
-if [[ "$1" =~ init.* ]]; then
+# when swiching user)
+if [[ "$1" == "kn-init" ]]; then
   export PATH="/opt/KubeNow/bin:$PATH"
 else
   export PATH="/KubeNow_root/bin:$PATH"
@@ -56,8 +56,12 @@ for arg in "$@"; do
 done
 
 # enter KubeNow user config path
+if [ ! -d "$DIRECTORY" ]; then
+  echo "Error: could not change dir to /KubeNow_root, exiting." >&2
+  exit 1
+fi
 cd "/KubeNow_root" || (
-  echo "Error: could not change dir to /KubeNow_root, exiting."
+  echo "Error: could not change dir to /KubeNow_root, exiting." >&2
   exit 1
 )
 
diff --git a/bin/kn b/bin/kn
--- a/bin/kn
+++ b/bin/kn
@@ -79,15 +79,15 @@ function docker_run() {
 function validate_pwd() {
   # Make sure that all of the needed files are in place
   if [ ! -f ssh_key ] || [ ! -f ssh_key.pub ]; then
-    echo >&2 "Error: ssh_key not found. Are you in the right directory?"
+    echo "Error: ssh_key not found. Are you in the right directory?" >&2
     exit 1
   fi
   if [ ! -f terraform.tfvars ]; then
-    echo >&2 "Error: terraform.tfvars not found. Are you in the right directory?"
+    echo "Error: terraform.tfvars not found. Are you in the right directory?" >&2
     exit 1
   fi
   if [ ! -f ansible.cfg ]; then
-    echo >&2 "Error: ansible.cfg not found. Are you in the right directory?"
+    echo "Error: ansible.cfg not found. Are you in the right directory?" >&2
     exit 1
   fi
 }
@@ -111,7 +111,7 @@ version)
 init)
   # Validate
   if [ "$#" -ne 3 ]; then
-    echo >&2 "Error: wrong number of argument for the init command"
+    echo "Error: wrong number of argument for the init command" >&2
     usage_init
     exit 1
   fi
@@ -119,7 +119,7 @@ init)
   host_cloud="$2"
   # Check for recognized cloud provider
   if ! grep -qw "$host_cloud" <<<"openstack gce azure aws"; then
-    echo >&2 "Error: unrecognized host cloud '$host_cloud'"
+    echo "Error: unrecognized host cloud '$host_cloud'" >&2
     usage_init
     exit 1
   fi
@@ -127,7 +127,7 @@ init)
   # shellcheck disable=SC2086,SC2046
   init_dir=$(cd $(dirname $3) && echo $PWD/$(basename $3))
   if [ -f "$init_dir" ] || [ -d "$init_dir" ]; then
-    echo >&2 "Error: $init_dir already exists"
+    echo "Error: $init_dir already exists" >&2
     usage_init
     exit 1
   fi
diff --git a/bin/kn-apply b/bin/kn-apply
--- a/bin/kn-apply
+++ b/bin/kn-apply
@@ -3,30 +3,33 @@
 # Exit immediately if a command exits with a non-zero status
 set -e
 
-HOST_CLOUD=$(grep -w "provider" terraform.tfvars |
+host_cloud=$(grep -w "provider" terraform.tfvars |
   cut -d "=" -f 2- |
   awk -F\" '{print $(NF-1)}')
 
-IMAGE_NAME=$(grep -w "boot_image" terraform.tfvars |
+image_name=$(grep -w "boot_image" terraform.tfvars |
   cut -d "=" -f 2- |
   awk -F\" '{print $(NF-1)}')
 
 # Check for recognized cloud provider
-if ! grep -qw "$HOST_CLOUD" <<<"openstack gce azure aws"; then
-  echo >&2 "Error: unrecognized host cloud '$HOST_CLOUD' in config file terraform.tfvars"
+if ! grep -qw "$host_cloud" <<<"openstack gce azure aws"; then
+  echo >&2 "Error: unrecognized host cloud '$host_cloud' in config file terraform.tfvars"
   exit 1
 fi
 
 # Import image (AWS doesn't need it)
-if [ "$HOST_CLOUD" = 'openstack' ] || [ "$HOST_CLOUD" = 'gce' ] || [ "$HOST_CLOUD" = 'azure' ]; then
+if [ "$host_cloud" = 'openstack' ] || [ "$host_cloud" = 'gce' ] || [ "$host_cloud" = 'azure' ]; then
   export GCE_ACCOUNT_FILE_PATH="$PWD/service-account.json"
   export TF_VARS_FILE="$PWD/terraform.tfvars"
-  export IMAGE_NAME
-  /KubeNow_root/bin/image-create-"$HOST_CLOUD".sh
+  export IMAGE_NAME="$image_name"
+  /KubeNow_root/bin/image-create-"$host_cloud".sh
 fi
+
 # Deploy
-terraform init --plugin-dir=/terraform_plugins "/KubeNow_root/$HOST_CLOUD"
+terraform init --plugin-dir=/terraform_plugins "/KubeNow_root/$host_cloud"
+
 # shellcheck disable=SC2086
-terraform apply $TERRAFORM_OPT "/KubeNow_root/$HOST_CLOUD"
+terraform apply $TERRAFORM_OPT "/KubeNow_root/$host_cloud"
+
 # shellcheck disable=SC2086
 ansible-playbook $ANSIBLE_OPT "/KubeNow_root/playbooks/install-core.yml"
diff --git a/bin/kn-destroy b/bin/kn-destroy
--- a/bin/kn-destroy
+++ b/bin/kn-destroy
@@ -3,16 +3,16 @@
 # Exit immediately if a command exits with a non-zero status
 set -e
 
-HOST_CLOUD=$(grep -w "provider" terraform.tfvars |
+host_cloud=$(grep -w "provider" terraform.tfvars |
   cut -d "=" -f 2- |
   awk -F\" '{print $(NF-1)}')
 
 # Check for recognized cloud provider
-if ! grep -qw "$HOST_CLOUD" <<<"openstack gce azure aws"; then
-  echo >&2 "Error: unrecognized host cloud '$HOST_CLOUD' in config file terraform.tfvars"
+if ! grep -qw "$host_cloud" <<<"openstack gce azure aws"; then
+  echo >&2 "Error: unrecognized host cloud '$host_cloud' in config file terraform.tfvars"
   exit 1
 fi
 
 # Destroy
 # shellcheck disable=SC2086
-terraform destroy $TERRAFORM_OPT "/KubeNow_root/$HOST_CLOUD"
+terraform destroy $TERRAFORM_OPT "/KubeNow_root/$host_cloud"
