adds upgrade function to kn

diff --git a/bin/kn b/bin/kn
--- a/bin/kn
+++ b/bin/kn
@@ -29,6 +29,8 @@ basic:
   scale                  resizes cluster after manual modifications in config.tfvars
   ssh <host>             ssh to <host> defined in ansible inventory file.
                          Default <host> is master
+  upgrade <version>      upgrade kn to <latest|latest-stable|master|"tag">
+                         Default <version> is the one currently in use
 kubernetes:
   kubectl                run kubectl on the master. More help: kn kubectl help
   helm                   run helm on the master. More help: kn helm help
@@ -114,6 +116,82 @@ function validate_pwd() {
   fi
 }
 
+function resolve_links() {
+  # parameters
+  source="$1"
+  # resolve $source until the file is no longer a symlink
+  while [ -h "$source" ]; do
+    dir="$(cd -P "$(dirname "$source")" && pwd)"
+    # if $dir was a relative symlink, we need to resolve it relative to
+    # the path where the symlink file was located
+    source="$(readlink "$source")"
+    [[ $dir != /* ]] && dir="$dir/$dir"
+  done
+  echo "$source"
+}
+
+function upgrade() {
+  # version is first arg or otherwise default
+  version=${1:-$kubenow_version}
+  echo "upgrade version: $version"
+  branch=""
+  case "$version" in
+  latest)
+    branch="$(curl https://api.github.com/repos/kubenow/KubeNow/releases |
+      jq -r '.[0].tag_name')"
+    ;;
+  latest-stable)
+    echo "lateststable"
+    branch="$(curl https://api.github.com/repos/kubenow/KubeNow/releases |
+      jq -r '[.[] | select(.prerelease==false) | .tag_name'][0])"
+    ;;
+  *)
+    branch="${version}"
+    ;;
+  esac
+
+  url="https://raw.githubusercontent.com/kubenow/KubeNow/$branch/bin/kn"
+
+  # Add a random suffix to prevent url caching
+  random="$(openssl rand -base64 16)"
+  url="$url?rnd=$random"
+
+  # Get full filename of this script
+  absolute_file="$(resolve_links "${BASH_SOURCE[0]}")"
+
+  echo "Download new version to /tmp"
+  tmpfile=$(mktemp)
+  curl -f "$url" -o "$tmpfile" || (
+    echo -e "\\nError trying to download file $url" >&2
+    echo -e "Are you sure \"$version\" is an available version?\\n" >&2
+    exit 1
+  )
+
+  # Verify that downloaded temp file is ok by executing kn help
+  echo "Verify downloaded file"
+  chmod +x "$tmpfile"
+  "$tmpfile" help >/dev/null 2>&1 || (
+    echo -e "\\nCould not verify functionality of downloaded kn script - skipping upgrade\\n" >&2
+    exit 1
+  )
+
+  # Copy new file over old (preserves file attr from original file)
+  echo "Replace file $absolute_file with downloaded"
+  rsync --no-perms --no-owner --no-group "$tmpfile" "$absolute_file" || (
+    echo -e "\\nError replacing file: $absolute_file - do you have sudo rights?\\n" >&2
+    exit 1
+  )
+
+  rm "$tmpfile"
+
+  # Pull latest docker
+  echo "Pull provisioners docker image"
+
+  docker pull "$KN_PROVISIONERS_IMG"
+
+  echo -e "\\nUpdated ok to version $KN_PROVISIONERS_IMG\\n"
+}
+
 function set_preset() {
   # parameters
   preset="$1"
@@ -186,6 +264,13 @@ help)
 
 version)
   echo "KubeNow version: $kubenow_version"
+  exit
+  ;;
+
+upgrade)
+
+  # shellcheck disable=SC2068
+  upgrade ${@:2}
   exit
   ;;
 
