Merged changes from openrisknet

diff --git a/bin/kn b/bin/kn
--- a/bin/kn
+++ b/bin/kn
@@ -27,6 +27,8 @@ basic:
   destroy                destroy deployment
   ssh <host>             ssh to <host> defined in ansible inventory file.
                          Default <host> is master
+  upgrade <version>      upgrade kn to <latest|latest-stable|master|"tag">
+
 kubernetes:
   kubectl                run kubectl on the master. More help: kn kubectl help
   helm                   run helm on the master. More help: kn helm help
@@ -42,6 +44,7 @@ cloud providers CLI:
 developers:
   bash                   run an interactive bash promt in the provisioners container
   kubetoken              generate and print a kubeadm token
+  git
 
 Options:
   -i, --docker-image <image>    specifies the provisioners docker image to be used.
@@ -95,6 +98,86 @@ function validate_pwd() {
     exit 1
   fi
 }
+#
+# Adapted from stackoverflow-questions-59895
+#
+function resolve_links() {
+  # parameters
+  source="$1"
+  # resolve $source until the file is no longer a symlink
+  while [ -h "$source" ]; do
+    dir="$(cd -P "$(dirname "$source")" && pwd)"
+    # if $dir was a relative symlink, we need to resolve it relative to
+    # the path where the symlink file was located
+    source="$(readlink "$source")"
+    [[ $dir != /* ]] && dir="$dir/$dir"
+  done
+  echo "$source"
+}
+
+#
+# Description of function
+#
+function upgrade() {
+  # parameters
+  version="$kubenow_version"
+  echo "upgrade version: $version"
+  branch=""
+  case "$version" in
+  latest)
+    branch="$(curl https://api.github.com/repos/kubenow/KubeNow/releases |
+      jq -r '.[0].tag_name')"
+    ;;
+  latest-stable)
+    echo "lateststable"
+    branch="$(curl https://api.github.com/repos/kubenow/KubeNow/releases |
+      jq -r '[.[] | select(.prerelease==false) | .tag_name'][0])"
+    ;;
+  *)
+    branch="${version}"
+    ;;
+  esac
+
+  url="https://raw.githubusercontent.com/kubenow/KubeNow/$branch/bin/kn"
+
+  # generate random suffix to prevent url caching
+  random="$(openssl rand -base64 16)"
+  url="$url?rnd=$random"
+
+  # get full filename of this script
+  absolute_file="$(resolve_links "${BASH_SOURCE[0]}")"
+
+  echo "Download new version to /tmp"
+  tmpfile=$(mktemp)
+  curl -f "$url" -o "$tmpfile" || (
+    echo >&2 -e "\nError trying to download file $url\n"
+    exit 1
+  )
+
+  # verify downloaded temp file is ok by executing kn help
+  echo "Verify downloaded file"
+  chmod +x "$tmpfile"
+  "$tmpfile" help >/dev/null 2>&1 || (
+    echo >&2 -e "\nCould not verify functionality of downloaded kn script - skipping upgrade\n"
+    exit 1
+  )
+
+  # copy file over old (preserves file attr from original file)
+  echo "Replace file $absolute_file with downloaded"
+  rsync --no-perms --no-owner --no-group "$tmpfile" "$absolute_file" || (
+    echo >&2 -e "\nCould not replace file: $absolute_file - do you have sudo rights?\n"
+    exit 1
+  )
+
+  rm "$tmpfile"
+
+  # pull latest docker
+  echo "Pull provisioners docker image"
+
+  docker pull "$KN_PROVISIONERS_IMG"
+
+  echo -e "\nUpdated ok to version $KN_PROVISIONERS_IMG\n"
+}
 
 ###########
 # Options #
@@ -102,7 +185,8 @@ function validate_pwd() {
 
 # Set defaults if not specified in the environment
 if [ -z "$KN_PROVISIONERS_IMG" ]; then
-  KN_PROVISIONERS_IMG="kubenow/provisioners:$kubenow_version"
+  tag="${kubenow_version/\//-}"
+  KN_PROVISIONERS_IMG="andersla/provisioners:$tag"
 fi
 
 # While current command starts with "-" parse options
@@ -136,6 +220,21 @@ help)
 
 version)
   echo "KubeNow version: $kubenow_version"
+  exit
+  ;;
+
+upgrade)
+
+  upgrade
+
+  exit
+  ;;
+
+install-autocomplete)
+  #/usr/local/etc/bash_completion.d
+  #/etc/bash_completion.d
+  echo >&2 "Error: could not find a suitable autocomplete path, e.g. /etc/bash_completion.d or /usr/local/etc/bash_completion.d"
+  echo "You could provide preferred installation path with argument --preferred=/path/to/bash_completion.d"
   exit
   ;;
 
