rename terraform.tfvars to config.tfvars

diff --git a/bin/kn b/bin/kn
--- a/bin/kn
+++ b/bin/kn
@@ -89,8 +89,8 @@ function validate_pwd() {
     echo "Error: ssh_key not found. Are you in the right directory?" >&2
     exit 1
   fi
-  if [ ! -f terraform.tfvars ]; then
-    echo "Error: terraform.tfvars not found. Are you in the right directory?" >&2
+  if [ ! -f config.tfvars ]; then
+    echo "Error: config.tfvars not found. Are you in the right directory?" >&2
     exit 1
   fi
   if [ ! -f ansible.cfg ]; then
@@ -101,7 +101,7 @@ function validate_pwd() {
 
 function validate_config() {
   # Get var from tfvars-file
-  provider=$(grep "provider" "terraform.tfvars" |
+  provider=$(grep "provider" "config.tfvars" |
     cut -d "=" -f 2- |
     awk -F\" '{print $(NF-1)}')
 
@@ -117,7 +117,7 @@ function validate_config() {
 
 function read_provisioner_image_var() {
   # Get var from tfvars-file
-  KN_PROVISIONERS_IMG=$(grep "provisioner_image" "terraform.tfvars" |
+  KN_PROVISIONERS_IMG=$(grep "provisioner_image" "config.tfvars" |
     cut -d "=" -f 2- |
     awk -F\" '{print $(NF-1)}')
   export KN_PROVISIONERS_IMG
diff --git a/bin/kn-apply b/bin/kn-apply
--- a/bin/kn-apply
+++ b/bin/kn-apply
@@ -4,7 +4,7 @@
 set -e
 
 # Read config file into variable as as json
-kn_config=$(json2hcl -reverse <terraform.tfvars)
+kn_config=$(json2hcl -reverse <config.tfvars)
 
 # Set variables from json-config
 host_cloud=$(jq -r '.provider' <<<"$kn_config")
@@ -12,14 +12,14 @@ image_name=$(jq -r '.boot_image' <<<"$kn_config")
 
 # Check for recognized cloud provider
 if ! grep -qw "$host_cloud" <<<"openstack gce azure aws"; then
-  echo >&2 "Error: unrecognized host cloud '$host_cloud' in config file terraform.tfvars"
+  echo >&2 "Error: unrecognized host cloud '$host_cloud' in config file config.tfvars"
   exit 1
 fi
 
 # Import image (AWS doesn't need it)
 if [ "$host_cloud" = 'openstack' ] || [ "$host_cloud" = 'gce' ] || [ "$host_cloud" = 'azure' ]; then
   export GCE_ACCOUNT_FILE_PATH="$PWD/service-account.json"
-  export TF_VARS_FILE="$PWD/terraform.tfvars"
+  export TF_VARS_FILE="$PWD/config.tfvars"
   export IMAGE_NAME="$image_name"
   /KubeNow_root/bin/image-create-"$host_cloud".sh
 fi
